Atostek/RustDDS

src/dds/participant.rs
This PR implements assert_liveliness as described on #15
The actual library code seems done, but I still need to write a unit test which I had trouble doing, looking for some advice on that front.
I also considered delegating the actual code to `DomainParticipant_Inner` from `DomainParticipant_Disc`- it seems all the other functions do so, except it isn't really needed here since I use only `self.discovery_command_channel` and it is already accessible from `DomainParticipant_Disc`.
=> Implement assert_liveliness in DomainParticipant

Cargo.toml
these targets are implicit, and don't need to be stated in the manifest
=> remove explicit 'example's from manifest

src/serialization/cdr_serializer.rs
best to use `write_all`, since the number of bytes written isn't handled
=> use 'write_all'

src/dds/message_receiver.rs, src/dds/reader.rs, src/dds/rtps_reader_proxy.rs, src/dds/rtps_writer_proxy.rs, src/discovery/data_types/spdp_participant_data.rs, src/discovery/data_types/topic_data.rs, src/discovery/discovery_db.rs, src/discovery/participant_proxy.rs, src/messages/submessages/info_reply.rs, src/network/util.rs, src/serialization/builtin_data_deserializer.rs, src/serialization/builtin_data_serializer.rs, src/structure/endpoint.rs, src/structure/locator.rs
removed the `LocatorList = Vec<Locator>` type alias
this adds unnecessary indirection. the term `LocatorList` is used in the spec to avoid using a concrete type, but this isn't necessary in code, since it's clear in context that a `Vec<Locator>` is a list of locators.
=> remove 'LocatorList'

.github/workflows/coverage.yml, src/dds/no_key/datawriter.rs
adds a test coverage workflow.
to see the benefit from this, you'd need to register an account with codecov.io (you can use github credentials)
=> add coverage workflow

.github/workflows/coverage.yml
My bad. The branch name should be 'master' not 'main'.
Copy-paste error on my part
=> Fix branch name in coverage workflow

src/dds/dp_event_loop.rs, src/dds/participant.rs, src/discovery/discovery_db.rs, src/messages/submessages/gap.rs
Since the ENTIRE DiscoveryDB is protected by a single lock, we cannot wait on it member value or partially access it member value without locking the entitre object.
To provide interrupt feature in such situation while minimize the performance loss, it need to store a extra copy of some variable and implemented in a indirect way.
This may not be a straightforward solution, but a workable solution without massive code change.
It may be better to let DiscoveryDB itself provide a internal thread safe protection. Then, it can be done in a more efficient way.
I may work on it in future.
=> Support interrupt while waitting for timeout in find topic

src/dds/fragment_assembler.rs, src/dds/helpers.rs, src/dds/with_key/datareader.rs, src/structure/duration.rs, src/structure/locator.rs, src/structure/sequence_number.rs
Some of the imported traits are in the standard prelude, and can be removed
=> remove std::prelude imports

src/dds/message_receiver.rs, src/dds/with_key/datareader.rs, src/discovery/data_types/spdp_participant_data.rs, src/lib.rs, src/serialization/builtin_data_deserializer.rs, src/structure/guid.rs
in an earlier PR i added `clippy::pedantic` lint warnings. This is *very* noisy in this code-base. This PR addresses a couple of those lints, and silences the rest.
=> fix or silence pedantic lints

src/dds/participant.rs
Just trying to make things consistent
=> Consistent omission of `use` from the rustdoc code examples for participant.rs

Cargo.toml, examples/turtle_teleop/main.rs, examples/turtle_teleop/ui.rs
- Organized `dev-dependencies`
- Removed unused dev dependencies
- Added some compilation conditionals to the turtle_teleop example to enable running `cargo test` on Windows
=> dev-dependencies clean up

src/dds/ddsdata.rs, src/dds/message_receiver.rs, src/discovery/discovery_db.rs, src/serialization/message.rs, src/structure/duration.rs
these attributes had blank lines after them, so weren't actually doing anything
=> fix attributes

.github/workflows/CI.yml
the old 'clippy-check' action is no longer maintained
=> update linting job

src/dds/message_receiver.rs
Hi,
I think I've found and corrected the bug wrt reception of fragmented messages. In UDP reception, the message was forwarded to the reader specified in fragmented packet header, reader_id  but the latter is set by dds::writer to Entity::Unknown, i.e. not specified. I've just added the code to distribute the packets to all readers waiting for data on this topic, as it was already implemented for not fragmented packets.
Best regards.
=> Corrected bug wrt reception of frag message with unknown reader_id

src/dds/reader.rs, src/serialization/cdr_deserializer.rs
Add a fix for IntercomDDS sending an empty string with no null terminator in some cases. 
Without this fix, an empty string will cause a panic
=> Add zero check for string bytes

src/security/cryptographic/builtin_types.rs
Also implements From and TryFrom traits to convert between general and plugin-specific types. The idea is that outside the plugin only the general ones are used, which contain serialized data, and they are converted to more useful types inside the plugin, which knows the correct deserialization etc.
Please check if this makes sense and cdr (de)serializer etc. are used correctly
=> Implement BuiltinCryptoToken and associated types

src/dds/key.rs, src/dds/pubsub.rs, src/dds/with_key/datareader.rs, src/dds/with_key/datasample.rs, src/dds/with_key/datasample_cache.rs, src/dds/with_key/datawriter.rs, src/dds/with_key/simpledatareader.rs, src/lib.rs, src/ros2/ros_node.rs, src/serialization/cdr_deserializer.rs, src/test/test_properties.rs
And other improvements:
- Don't deny clippy lints to avoid breakage when new lints are created
- Add `Key` bound on `Keyed::K` so that we don't need to specify it on every usage
=> Fix overly strict lifetime requirements for deserialization helpers

Cargo.toml, src/mio_source.rs, src/network/udp_listener.rs, src/network/udp_sender.rs
These changes restore Windows compatibility. Event notification is done using a normal socket instead of a socketpair because socketpair does not use sockets under the hood in Windows. The udp sender and udp listener needed to use mio 8 because mio 6 refused to actually send data. Some tests still seem to fail on Windows.
=> Attempt at restoring Windows compatibility

src/mio_source.rs
Hi there,
Thanks for creating this nice repo. I suggest I catch a tiny bug in `mio_source.rs`: the type of `send_mio_socket ` in struct `PollEventSender` should be `Arc<Mutex<...>>`.
Best,
Levi
=> Fix send_mio_socket type when target_os="windows"

src/dds/qos.rs
Hello,
We saw ticket #297 and had already did some related work in our local repo.
Our scope was a bit different: We needed to make the `QosPolicyBuilder` ser/deserializable, to be able to load it from configuration files, then append/modify QoS Policies before building the `QosPolicies` struct. It was not a big deal to increase the scope to `QosPolicies` stuct.
Thus, I suggest this pull-request to resolve ticket #297.
> I did not find any contributing guidelines, don't hesitate to tell me if the format doesn't suit you.
Regards,
Thomas
- Added `Serialize` and `Deserialize` derives to all QoS policies, and to the `QosPolicies` + `QosPolicyBuilder` structs.
- Added missing derives to the `QosPolicyBuilder` for ease of use (Added derives are `Clone`, `Debug`, `PartialEq`, `Eq`). Its derives …
=> Make qos serializable

src/network/udp_sender.rs
Removed the logic that tries to bind all interfaces to a UDP socket on Windows. I do not understand why this would be necessary. The result seems to be that the socket binds to the earliest listed interface it can bind to and fails all other interfaces. This means that RustDDS fails to send unicast UDP messages to any devices that are not available to that first interface. Binding to "0.0.0.0" works on Windows so I removed the conditional compilation syntax. The fact that this code was present leads me to believe that this fixed something earlier, right now I cannot determine what this was.
=> Fixed Windows UDP unicast only working on a single network interface

examples/async_shapes_demo/main.rs, examples/hello_world_subscriber/main.rs, examples/no_key_async_usage_example/main.rs, src/dds/no_key/datareader.rs, src/dds/with_key/datareader.rs, src/lib.rs
This pull-request resolve issue #298.
- Renamed current `async_sample_stream` (bare) to `async_bare_sample_stream`.
- Implemented the non-bare `async_sample_stream`, copying the same machinery as bare, replacing calls to `take_bare` by `take`.
In async examples, replaced calls to the old `async_sample_stream` (bare) to the new `async_sample_stream` (non-bare), updating the sample handling.
One now has the option to access `SampleInfo` from the async reader interface.
All users of the crate will have to adapt code using the async interface either by changing to the `async_bare_sample_stream` or adapt their `Sample` handlers if they choose to use the non-bare `async_sample_stream` interface.
=> Access SampleInfo from async reader interface

Cargo.toml, src/discovery/discovery.rs, src/network/constant.rs, src/network/udp_listener.rs, src/network/udp_sender.rs, src/network/util.rs
Previously, the `rustdds::util::get_local_multicast_ip_addrs` function didn't account for whether an interface had the multicasting flag. 
This PR adds the `pnet` crate as a dependency to handle that properly. :D
I also fixed the crate's known-flaky tests. The first batch were from the `discovery` module, and the failures were just port misalignments. The other failures stemmed from incorrect handling of the internal `mio::net::UdpSocket` - it was set to be async, but the test functions to read weren't accounting for that.
If you'd like those in another PR, please let me know!
(I license all changes included in this patch set under the Apache License, version 2.0.)
=> Account for multicasting support when finding capable IPs

src/messages/submessages/data_frag.rs
[div_ceil](https://doc.rust-lang.org/std/primitive.u32.html#method.div_ceil) has been stabilized since 1.72
=> calculate DataFrag FragmentNumber with div_ceil
